apiVersion: apps/v1
kind: Deployment
metadata:
  name: sf-angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sf-angular
  template:
    metadata:
      labels:
        app: sf-angular
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: sf-angular
        image: javascriptjenkins/sf-angular:latest
        ports:
        - containerPort: 4200
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - name: applogs-persistent-storage
          mountPath: /logs
      volumes:
      - name: applogs-persistent-storage
        persistentVolumeClaim:
          claimName: applogs-pv-claim