apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
  - port: 9300
    name: tcp-9300
    protocol: TCP
    targetPort: 9300
  - port: 9200
    name: tcp-9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: es-master