apiVersion: v1
kind: Service
metadata:
  name: default-backend
  namespace: ingress
spec:
  ports:
  - port: 80
    name: tcp-80
    protocol: TCP
    targetPort: 8080
  selector:
    app: default-backend
