apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  ports:
  - port: 80
    name: tcp-80
    protocol: TCP
    targetPort: 8080
  selector:
    app: ingress-nginx
