apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mymasteringress
  namespace: ingress-nginx
spec:
  rules:
  - host: sportvvs.com
    http:
      paths:
      - backend:
          serviceName: ingress-nginx
          servicePort: 18080
        path: /nginx_status
