apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbscrape
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sbscrape
  template:
    metadata:
      labels:
        app: sbscrape
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: sbscrape
        image: javascriptjenkins/sb-scrape:latest
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_HOST
            value: my-sql
          - name: MYSQL_PASS
            value: my-secret-pw
          - name: MYSQL_DDL_AUTO
            value: update
          - name: RUN_HEADLESS
            value: 'true'
          - name: HYDRATE_INIT_DATA
            value: 'false'
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - name: applogs-persistent-storage
          mountPath: /logs
      volumes:
      - name: applogs-persistent-storage
        persistentVolumeClaim:
          claimName: applogs-pv-claim