- hosts: master
  become: yes
  tasks:

    - name: delete existing kibana deployment
      become: yes
      become_user: ubuntu
      shell: sudo kubectl delete deployment kibana -n=ingress
      args:
        chdir: $HOME

    - name: create kibana deployment
      become: yes
      become_user: ubuntu
      shell: sudo kubectl create -f https://raw.githubusercontent.com/JavascriptJenkins/mr-kube-baby/master/kube-cluster/yamls/kibana/kibana-deployment.yaml -n=ingress
      args:
        chdir: $HOME

    - name: create kibana service with np
      become: yes
      become_user: ubuntu
      shell: sudo kubectl create -f https://raw.githubusercontent.com/JavascriptJenkins/mr-kube-baby/master/kube-cluster/yamls/kibana/kibana-service-np.yaml -n=ingress
      args:
        chdir: $HOME