apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-sql
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: my-sql
    spec:
      selector:
        matchLabels:
          app: my-sql
      terminationGracePeriodSeconds: 60
      containers:
      - name: mysql
        image: mysql:5.7.22
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: my-secret-pw
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
