apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: kibana
        image: kibana:6.6.1
        ports:
        - containerPort: 5601
        env:
          - name: ELASTICSEARCH_URL
            value: 'elasticsearch:9200'
        resources:
          limits:
            cpu: 800m
            memory: 1000Mi
          requests:
            cpu: 200m
            memory: 512Mi
